name: Functional
description: Performs functional tests checks
inputs:
  project:
    description: "Playwright project to use"
    required: true
    default: "chromium"
  apiKey:
    description: "Replay.io API Key"
  issue-number:
    description: "Issue / Pull Request on which to comment results"
  upload-all:
    description: "Upload all replays"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - uses: bahmutov/npm-install@v1
    - run: npx playwright install-deps
      shell: sh
    - run: npx playwright install
      shell: sh
    - run: npm run build
      shell: sh
    - uses: replayio/action-playwright@v0.3.1
      with:
        command: npm run test:functional --
        issue-number: ${{ inputs.issue-number }}
        project: ${{ inputs.project }}
        apiKey: ${{ inputs.apiKey }}
        upload-all: true
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: visual-snapshots-diff
        path: test-results
