name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    name: Linting and type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/typescript

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/unit

  functional-tests:
    name: Functional tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/functional
        with:
          project: "replay-chromium"
          issue-number: ${{ github.event.pull_request.number }}
          apiKey: ${{ secrets.RECORD_REPLAY_API_KEY }}
